; sleep.g
; called when M1 (Sleep) is being processed
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Mar 24 2019 20:32:33 GMT-0700 (Pacific Daylight Time)
G10 P0 S60
M116 P0 ;Wait for Tool 1
M81 ;Turn off ATX power