; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Mar 24 2019 20:32:34 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

